### ISSUE TITLE
parser panics instead of returning an error

### ISSUE THREAD

**Issue by theKlisha** [martinohmann/hcl-rs#284] opened 2023-08-16 17:57 UTC
Provided code snippet causes panic.

```rs
let str = r#"
  locals {
    test = {
      a = b// this comment breaks the parser
      c = d // but this one doesn't
    }
  }
"#;

let _: Result<hcl::Body, _> = hcl::from_str(str);
```

tested on version `0.16.3`

**Comment by martinohmann** [comment] 2023-08-23 19:34
Hi there!

Thanks for the bug report and the reproducer.

I'm trying to get this fixed with the next releasebut it may take a couple of days since i just moved to a new home and still need to unpack stuff in order to set up my workspace again 😉.

**Closed** 2023-08-24 20:13 UTC
Labels: bug

**Comment by martinohmann** [comment] 2023-08-24 20:18
@theKlisha Got to it earlier than expected. I just released the fix as 0.16.4.

**Comment by theKlisha** [comment] 2023-08-24 21:39
Thanks for the fix!
